version: '3.4'

services:
  algotrading:
    image: algotrading
    volumes:
      - /Users/johnqiangzhang/Documents/open_source/algoTrading:/app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "python setup.py develop --user  && python /app/algotrading/scripts/draw_single_plot.py --extra stock_list=shuping --extra report_format=html"]
